version: '3'
services:
  host-injector:
    container_name: host_c
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
      - '/etc/hosts:/tmp/hosts'
    image: dvdarias/docker-hoster
  redis:
    hostname: redis.wlp.com
    image: redis:latest
    container_name: rd01
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  worker:
    hostname: celery.wlp.com
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: celery.Dockerfile
    volumes:
      - .:/opt/metadata-extraction
    command: celery -A __init__.client worker --loglevel=info -f celery.logs -Ofair -c 2
    tty: true
  app:
    hostname: app.wlp.com
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/opt/metadata-extraction
    container_name: app01
    ports:
      - "5000:5000"
    command: python3 server/__init__.py
    tty: true
  flower:
    hostname: flower.wlp.com
    image: mher/flower
    container_name: flower01
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - "8888:8888"
volumes:
  redis:
