from .controllerMapper import *
from helpers import model_helpers

user_controller = UserController()
customer_controller = CustomerController()
ticket_status_controller = TicketStatusController()
creation_milestones_controller = CreationMilestonesController()
pickup_milestones_controller = PickupMilestonesController()
inventory_milestones_controller = InventoryMilestonesController()
assignment_milestones_controller = AssignmentMilestonesController()
incomplete_delivery_milestones_controller = IncompleteDeliveryMilestonesController()
delivery_milestones_controller = DeliveryMilestonesController()
ticket_controller = TicketController()

# Upon Import, this dictionary is autogenerated
_model_to_cntrl_map = {}

_all_controllers = [
    user_controller,
    customer_controller,
    ticket_status_controller,
    creation_milestones_controller,
    pickup_milestones_controller,
    inventory_milestones_controller,
    assignment_milestones_controller,
    incomplete_delivery_milestones_controller,
    delivery_milestones_controller,
    ticket_controller,
]

def _build_model_to_cntrl_map():
    for controller in _all_controllers:
        _model_to_cntrl_map[controller.model] = controller
        controller._set_model_map_methods(get_controller_by_model, get_controller_by_model_name)

def get_controller_by_model(model):
    return _model_to_cntrl_map[model]

def get_controller_by_model_name(model_name: str):
    model = model_helpers.get_model_by_name(model_name)
    return _model_to_cntrl_map[model]

_build_model_to_cntrl_map()

