import sys
controllers_module = sys.modules[__name__]
from .controllerMapper import *
from helpers import model_helpers

controllers_module.user_controller = UserController()
controllers_module.customer_controller = CustomerController()
controllers_module.ticket_status_controller = TicketStatusController()
controllers_module.creation_milestones_controller = CreationMilestonesController()
controllers_module.pickup_milestones_controller = PickupMilestonesController()
controllers_module.inventory_milestones_controller = InventoryMilestonesController()
controllers_module.assignment_milestones_controller = AssignmentMilestonesController()
controllers_module.incomplete_delivery_milestones_controller = IncompleteDeliveryMilestonesController()
controllers_module.delivery_milestones_controller = DeliveryMilestonesController()
controllers_module.ticket_controller = TicketController()

# Upon Import, this dictionary is autogenerated
_model_to_cntrl_map = {}

_all_controllers = [
    user_controller,
    customer_controller,
    ticket_status_controller,
    creation_milestones_controller,
    pickup_milestones_controller,
    inventory_milestones_controller,
    assignment_milestones_controller,
    incomplete_delivery_milestones_controller,
    delivery_milestones_controller,
    ticket_controller,
]

def _build_model_to_cntrl_map():
    for controller in _all_controllers:
        _model_to_cntrl_map[controller.model] = controller
        controller._set_model_map_methods(get_controller_by_model, get_controller_by_model_name)

def get_controller_by_model(model):
    if model and model in _model_to_cntrl_map:
        return _model_to_cntrl_map[model]
    return None

def get_controller_by_model_name(model_name: str):
    model = model_helpers.get_model_by_name(model_name)
    if model and model in _model_to_cntrl_map:
        return _model_to_cntrl_map[model]
    return None

def recreate_singleton_objects():
    controllers_module.user_controller = UserController()
    controllers_module.customer_controller = CustomerController()
    controllers_module.ticket_status_controller = TicketStatusController()
    controllers_module.creation_milestones_controller = CreationMilestonesController()
    controllers_module.pickup_milestones_controller = PickupMilestonesController()
    controllers_module.inventory_milestones_controller = InventoryMilestonesController()
    controllers_module.assignment_milestones_controller = AssignmentMilestonesController()
    controllers_module.incomplete_delivery_milestones_controller = IncompleteDeliveryMilestonesController()
    controllers_module.delivery_milestones_controller = DeliveryMilestonesController()
    controllers_module.ticket_controller = TicketController()

_build_model_to_cntrl_map()

