version: '3'
services:
  postgres:
    container_name: postgres_c
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - env/postgres.env
    environment:
      POSTGRES_DB: tenant_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
